CREATE DATABASE LIVRARIA;

USE LIVRERIA;

CREATE TABLE LIVROS(

	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10, 2),
	UF CHAR(2),
	ANO INT(4)
);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) 
VALUES
('Cavaleiro Real', 'Ana Claudia', 'F', 465, 'Atlas', 49.0, 'RJ', 2009),
('SQL para leigos', 'João Nunes', 'M', 450, 'Addison', 98.0, 'SP', 2018),
('Receitas Caseiras', 'Celia Tavares', 'F', 210, 'Atlas', 45.0, 'RJ', 2008),
('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', 2018),
('Habitos Saudáveis', 'Eduardo Santos', 'M', 630, 'Beta', 150.98, 'RJ', 2019),
('A casa Marron', 'Hermes Macedo', 'M', 250, 'Bubba', 60.0, 'MG', 2016),
('Estacio Querido', 'Geraldo Francisco', 'M', 310, 'Insignia', 100.0, 'ES', 2015),
('Pra sempre amigas', 'Leda Silva', 'F', 510, 'Insignia', 78.98, 'ES', 2011),
('Copas Insequecíveis', 'Marco Alcantra', 'M', 200, 'Larson', 130.98, 'RS', 2018),
('O poder da mente', 'Clara Mafra', 'F', 120, 'Continental', 56.58, 'RS', 2017);


-- 1-TRAZER TODOS OS DADOS--
SELECT * FROM LIVROS;

-- 2-TRAZER O NOME DOS LIVROS E DAS EDITORAS
SELECT NOME, EDITORA FROM LIVROS;

-- 3-TRAZER O NOME DO LIVRO, E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO
SELECT LIVRO, UF FROM LIVROS WHERE SEXO = 'M';

-- 4-TRAZER O NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO
SELECT LIVRO, PAGINAS, SEXO FROM LIVROS WHERE SEXO = 'F';

-- 5-TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO
SELECT VALOR, UF FROM LIVROS WHERE UF='SP';

-- 6-TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO.
SELECT AUTOR, SEXO FROM LIVROS WHERE SEXO = 'M' AND (UF='SP' OR UF='RJ');


-- OPERAÇÕES LOGICAS
/*
OR -> PARA QUE A SAÍDA DA QUERY SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDIÇÃO SEJA VERDADEIRA
AND -> PARA QUE A SAÍDA SEJA VERDADE, TODAS AS CONDIÇÕES PRECISAM SER VERDADEIRAS
*/

/*
/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTES VALUES('JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTES VALUES('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSERT INTO CLIENTES VALUES('JORGE','M',NULL,885755896,58748895,'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

--

SELECT NOME, SEXO, ENDERECO FROM CLIENTES WHERE SEXO ='M' OR ENDERECO LIKE '%RJ';

--FUNÇÕES DE AGREGAÇÕES
 /* SELECT COUNT( * ) AS "QUANTIDADE DE RESGISTROS" FROM CLIENTE;  -> CONTA TODOS OS REGRISTROS DA TABELA*/

SELECT SEXO, COUNT(*) FROM CLIENTES
WHERE SEXO = "M" GROUP BY SEXO;

/*EXERCICIO COM A DATABASE EXERCICIO */

-- TRAGA OS FUNCIONARIOS QUE TRABALHAM NO DEPARTAMENTO DE FILMES OU ROUPAS

SELECT DEPARTAMENTO, COUNT(*) FROM FUNCIONARIOS;

SELECT COUNT(*), DEPARTAMENTO FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO
ORDER BY 1;

SELECT * FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'Roupas' OR DEPARTAMENTO = 'Filmes';

-- O GESTOR DE MARKETING PEDIU A LISTA DAS FUNCIONARIAS QUE TRABALHEM DEPARTAMENTO
--DE FILMES OU LAR. ELE NECESSITA EVNAIR UM EMAIL PARA AS COLAVORADORAS
--DESSES DOIS SETORES.

SELECT NOME, DEPARTAMENTO, SEXO FROM FUNCIONARIOS
WHERE (DEPARTAMENTO = 'Lar' OR DEPARTAMENTO = 'Filmes') AND SEXO = 'Feminino';

SELECT * FROM FUNCIONARIOS
WHERE
(DEPARTAMENTO = 'Lar' AND SEXO = 'Feminino') 
OR
(DEPARTAMENTO = 'Filmes' AND SEXO = 'Feminino');

-- COMO ESTAMOS TRABALHANDO COM AND, COLOCAMOS O DEPARTAMENTO PRIMEIRO, POIS ELE
--IRPA CHECAR A SEGUNDA CONDIÇÃO UM UMERO MENOR DE VEZES


-- TRAGA OS FUNCIONARIOS DO SEXO MASCULINO OU OS FUNCIONARIOS QUE
--TRABALHEM NO JARDIM.

SELECT COUNT(*) FROM FUNCIONARIOS
WHERE SEXO = 'Masculino';

SELECT COUNT(*) FROM FUNCIONARIOS
WHERE DEPARTAMENTO = 'Jardim';

SELECT NOME, DEPARTAMENTO, SEXO FROM FUNCIONARIOS
WHERE SEXO = 'Masculino' OR DEPARTAMENTO = 'Jardim';

/* TRATAMENTO CAMPOS NULOS */

-- OS CAMPOS NULOS SÃO VAZIO, SÃO ENCONTRADOS COM O COMANDO
-- CAMPO IS NULL

-- ENCONTRE OS CAMPOS EMAIL NULL NO BANCO PROJETOS

USE PROJETO;

SHOW TABLES;

DESC TABLES;

SELECT * FROM CLIENTES
WHERE EMAIL IS NULL;

