CREATE DATABASE LIVRARIA;

USE LIVRERIA;

CREATE TABLE LIVROS(

	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10, 2),
	UF CHAR(2),
	ANO INT(4)
);

INSERT INTO LIVROS(LIVRO, AUTOR, SEXO, PAGINAS, EDITORA, VALOR, UF, ANO) 
VALUES
('Cavaleiro Real', 'Ana Claudia', 'F', 465, 'Atlas', 49.0, 'RJ', 2009),
('SQL para leigos', 'João Nunes', 'M', 450, 'Addison', 98.0, 'SP', 2018),
('Receitas Caseiras', 'Celia Tavares', 'F', 210, 'Atlas', 45.0, 'RJ', 2008),
('Pessoas Efetivas', 'Eduardo Santos', 'M', 390, 'Beta', 78.99, 'RJ', 2018),
('Habitos Saudáveis', 'Eduardo Santos', 'M', 630, 'Beta', 150.98, 'RJ', 2019),
('A casa Marron', 'Hermes Macedo', 'M', 250, 'Bubba', 60.0, 'MG', 2016),
('Estacio Querido', 'Geraldo Francisco', 'M', 310, 'Insignia', 100.0, 'ES', 2015),
('Pra sempre amigas', 'Leda Silva', 'F', 510, 'Insignia', 78.98, 'ES', 2011),
('Copas Insequecíveis', 'Marco Alcantra', 'M', 200, 'Larson', 130.98, 'RS', 2018),
('O poder da mente', 'Clara Mafra', 'F', 120, 'Continental', 56.58, 'RS', 2017);


-- 1-TRAZER TODOS OS DADOS--
SELECT * FROM LIVROS;

-- 2-TRAZER O NOME DOS LIVROS E DAS EDITORAS
SELECT NOME, EDITORA FROM LIVROS;

-- 3-TRAZER O NOME DO LIVRO, E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO
SELECT LIVRO, UF FROM LIVROS WHERE SEXO = 'M';

-- 4-TRAZER O NOME DO LIVRO E O NÚMERO DE PÁGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMININO
SELECT LIVRO, PAGINAS, SEXO FROM LIVROS WHERE SEXO = 'F';

-- 5-TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO
SELECT VALOR, UF FROM LIVROS WHERE UF='SP';

-- 6-TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO.
SELECT AUTOR, SEXO FROM LIVROS WHERE UF='SP' OR UF='RJ' ORDER BY SEXO;
